// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChineseNameInput","status":true,"description":"允許玩家使用鍵盤輸入中文名稱","parameters":{"MaxLength":"6"}},
{"name":"ParticipantID","status":true,"description":"讓受試者輸入辨識碼（手機後3碼＋生日後4碼）","parameters":{"Phone Variable ID":"11","Birthday Variable ID":"12"}},
{"name":"DataUploader","status":true,"description":"遊戲結束時上傳資料到 Google Sheets","parameters":{"Google Script URL":"https://script.google.com/macros/s/AKfycbzGEOOZsa-p4hAMB75CYGFkfgu7tBEZ9yeOUzBL8sR4Y70bGpOAv4RDztoozvOJ9Ze78Q/exec","Condition Variable":"1","BLM Variable":"2","Reward Variable":"3","Accountability Variable":"4","Decision1 Variable":"5","Decision2 Variable":"6","Decision3 Variable":"7","Decision4 Variable":"8","Decision5 Variable":"9","Decision6 Variable":"10","Phone Variable":"11","Birthday Variable":"12","Rewardnum Variable":"13","BLMnum Variable":"14","Accountnum Variable":"15"}},
{"name":"ConditionDecoder","status":true,"description":"將 condition 編號解碼為 BLM、Reward、Accountability 三個變數","parameters":{"Condition Variable ID":"1","BLM Variable ID":"2","Reward Variable ID":"3","Accountability Variable ID":"4"}}
];
